apiVersion: v2
name: vault-unseal-cronjob
description: A chart for unseal Vault cron job
type: application
version: "0.5.0"
appVersion: "0.5.0"

keywords:
  - cron
home: "https://github.com/omegion"
sources:
  - "https://github.com/omegion"
maintainers:
  - name: omegion
    email: oomegion@gmail.com