apiVersion: v2
name: vault-unseal-cronjob
description: A chart for unseal Vault cron job
type: application
version: "0.6.0"
appVersion: "0.8.0"
home: "https://charts.omegion.dev"
sources:
  - "https://github.com/omegion/vault-unseal"
maintainers:
  - name: omegion
    email: oomegion@gmail.com
keywords:
  - vault
  - unseal
  - cron
